name: linuxserver-firefox
services:
  app:
    cpu_shares: 90
    command: []
    deploy:
      resources:
        limits:
          memory: 15388M
    environment:
      - FIREFOX_CLI=
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Madrid
    image: linuxserver/firefox:0.24.04
    labels:
      icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/firefox-logo.png
    ports:
      - target: 3000
        published: "3069"
        protocol: tcp
      - target: 3001
        published: "3068"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/firefox/config
        target: /config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: FIREFOX_CLI
          description:
            en_us: Specify one or multiple Firefox CLI flags, this string will be passed to
              the application in full.
      ports:
        - container: "3000"
          description:
            en_us: "Container Port: 3000"
      volumes:
        - container: /config
          description:
            en_us: Appdata
    devices: []
    cap_add: []
    networks:
      - default
    privileged: false
    container_name: ""
    hostname: ""
networks:
  default:
    name: linuxserver-firefox_default
x-casaos:
  architectures:
    - amd64
    - arm64
  author: WisdomSky
  category: LinuxServer.io
  description:
    en_us: "Visit homepage: https://hub.docker.com/r/linuxserver/firefox/"
  developer: LinuxServer.io
  hostname: ""
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/firefox-logo.png
  index: /
  is_uncontrolled: false
  main: app
  port_map: "3069"
  project_url: https://firefox-project.org/
  scheme: http
  store_app_id: linuxserver-firefox
  tagline:
    en_us: Browser, also known as Mozilla Firefox or simply Firefox, is a free and
      open-source web browser developed by the Mozilla Foundation and its
      subsidiary, the Mozilla Corporation. Firefox uses the Gecko layout engine
      to render web pages, which implements current and anticipated web
      standards.
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/firefox-logo.png
  title:
    custom: ""
    en_us: Firefox
