name: linuxserver-steamos
services:
  app:
    cpu_shares: 90
    command: []
    deploy:
      resources:
        limits:
          memory: 15387M
    environment:
      - DRINODE=
      - HOST_IP=
      - PGID=1000
      - PUID=1000
      - RESOLUTION=
      - STARTUP=
      - TZ=Europe/Madrid
    image: linuxserver/steamos:2025-01-19-ls95
    labels:
      icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/steamos-logo.png
    ports:
      - target: 3000
        published: "3034"
        protocol: tcp
      - target: 3001
        published: "3035"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/steamos/config
        target: /config
      - type: bind
        source: /dev/input
        target: /dev/input
      - type: bind
        source: /run/udev/data
        target: /run/udev/data
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: Run 'id [USER]' for the owner of the host volume directories to get the
              UID to use here.
        - container: PGID
          description:
            en_us: Run 'id [USER]' for the owner of the host volume directories to get the
              GID to use here.
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: DRINODE
          description:
            en_us: Specify the render device (GPU) for the contianer to use.
        - container: HOST_IP
          description:
            en_us: Specify the IP of the host, needed for LAN Remote Play. [OPTIONAL]
        - container: STARTUP
          description:
            en_us: KDE to boot into desktop mode, BIGPICTURE to boot into gamescope.
              [OPTIONAL]
        - container: RESOLUTION
          description:
            en_us: When booting into BIGPICTURE mode the screen resolution will be bound to
              this value. [OPTIONAL]
    devices: []
    cap_add: []
    networks:
      - default
    privileged: false
    container_name: ""
    hostname: ""
networks:
  default:
    name: linuxserver-steamos_default
x-casaos:
  architectures:
    - amd64
  author: WisdomSky
  category: LinuxServer.io
  description:
    en_us: SteamOS is an Arch based Linux distribution made by Valve Software. This
      container is a vanilla Arch install with Steam repositories added for
      software support. This container will only work with modern AMD/Intel GPUs
      on a real Linux Host
  developer: LinuxServer.io
  hostname: ""
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/steamos-logo.png
  index: /
  is_uncontrolled: false
  main: app
  port_map: "3034"
  scheme: http
  store_app_id: linuxserver-steamos
  tagline:
    en_us: An Arch based Linux distribution made by Valve Software. This container
      is a vanilla Arch install with Steam repositories added for software
      support. This container will only work with modern AMD/Intel GPUs on a
      real Linux Host
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/steamos-logo.png
  title:
    custom: ""
    en_us: Steamos
